export const DEFAULT_CATEGORIES = [
  'Food & Dining',
  'Transport',
  'Shopping',
  'Utilities',
  'Groceries',
  'Entertainment',
  'Healthcare',
  'Education',
  'Rent & Housing',
  'Salary',
  'Freelance',
  'Investment',
  'Travel',
  'Insurance',
  'Office Supplies',
  'Subscriptions',
  'Gifts & Donations',
  'Other',
] as const;

export type Category = (typeof DEFAULT_CATEGORIES)[number];

export const MERCHANT_CATEGORY_MAP: Record<string, string> = {
  'swiggy': 'Food & Dining',
  'zomato': 'Food & Dining',
  'food': 'Food & Dining',
  'restaurant': 'Food & Dining',
  'dominos': 'Food & Dining',
  'mcdonalds': 'Food & Dining',
  'uber': 'Transport',
  'ola': 'Transport',
  'metro': 'Transport',
  'irctc': 'Transport',
  'rapido': 'Transport',
  'amazon': 'Shopping',
  'flipkart': 'Shopping',
  'myntra': 'Shopping',
  'ajio': 'Shopping',
  'airtel': 'Utilities',
  'jio': 'Utilities',
  'vodafone': 'Utilities',
  'electricity': 'Utilities',
  'water': 'Utilities',
  'bigbasket': 'Groceries',
  'blinkit': 'Groceries',
  'zepto': 'Groceries',
  'instamart': 'Groceries',
  'netflix': 'Subscriptions',
  'spotify': 'Subscriptions',
  'hotstar': 'Subscriptions',
  'prime': 'Subscriptions',
  'hospital': 'Healthcare',
  'pharmacy': 'Healthcare',
  'apollo': 'Healthcare',
  'medplus': 'Healthcare',
};
